name: advanced_salomon_bottom_bar
description: Yet another bottom navigation bar, but with a few key promises and advancements.
version: 3.3.3
homepage: https://github.com/anmolthedeveloper/advanced_salomon_bottom_bar

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
